### ISSUE TITLE
Buildozer does not install build tools automatically with fresh install

### ISSUE THREAD

**Issue by chozabu** [kivy/buildozer#146]
A fresh clone of buildozer, attempting to build a basic application fails due to buildozer not installing build tools.

This can be worked around by waiting for buildozer to fail, browsing to buildozers android SDK installation, launching the manager and installing build tools version 20, ensuring to unmark any packages checked by default!

kived mentions it may be trying to install build tools version 21 - which does not exist.
##

**Comment by tito** [comment]
This is fixed, please reopen the day it will break again :)

**Comment by souzal** [comment]
I have the same problem with buildozer, I'm running on Linux 64-bit, did the installation of buildozer as the following site: 

http://wiki.labomedia.org/index.php/Kivy_Buildozer_pour_cr%C3%A9er_une_application_Android_avec_un_script_python

Through this site I found this post, I performed the described steps and the problem persists. Thank you in advance for your help.

![01](https://cloud.githubusercontent.com/assets/12912924/8185119/b0c98716-1442-11e5-8037-d7693c1e1a42.jpg)
![02](https://cloud.githubusercontent.com/assets/12912924/8185120/b0e77442-1442-11e5-8586-fe1aa471f030.jpg)

**Comment by tottil** [comment]
I have the same problem with buildozer: 
"subprocess.CalledProcessError: Command '['ant', 'debug']' returned non-zero exit status 1"
 
I'm running on Linux 64-bit, did the installation of buildozer as the following site:

http://wiki.labomedia.org/index.php/Kivy_Buildozer_pour_cr%C3%A9er_une_application_Android_avec_un_script_python

Through this site I found this post, I performed the described steps and the problem persists. Thank you in advance for your help.
![01](https://cloud.githubusercontent.com/assets/12912924/8185405/784aee3c-1444-11e5-85ca-773afa70e2f9.jpg)

**Comment by kived** [comment]
It has been broke again for a while.

**Comment by elbow-jason** [comment]
This is broken as of today (27 AUG 2015).

**Comment by stuaxo** [comment]
Bah, just hit this.

**Comment by MichaelCurrie** [comment]
@Laspimon how do I update SDK tools to version 0.23 as you suggest above?  I'm stuck on the same screen you were.

**Comment by Laspimon** [comment]
Glad you figured it out.

**Comment by stuaxo** [comment]
So the bug is that the out-of-box experience needs to download SDK tools version 23.0 from the get go ?

**Comment by erikvanelten** [comment]
I installed 20 and 23, now I get this... Now what?

BUILD FAILED
/home/erik/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/erik/.buildozer/android/platform/android-sdk-21/tools/ant/build.xml:655: Execute failed: java.io.IOException: Cannot run program "/home/erik/.buildozer/android/platform/android-sdk-21/build-tools/23.0.1/aidl": error=2, No such file or directory

**Comment by evbo** [comment]
Still broken. I had to manually update 3 times so far. After each update, I reload the update manager to find there is yet another required update...

**Comment by redfast00** [comment]
This probably broke again: see #357

**Comment by evbo** [comment]
Yeah, the major issue that isn't captured in the readme is any Buildozer build MUST be run on the disk of the virtualmachine - not a shared folder with your host machine.

**Comment by NumesSanguis** [comment]
Still existing, I had to open `~/.buildozer/android/platform/android-sdk-21/tools/android` and update around 4 times.
Ubuntu 16.04 with Python 3.5

**Comment by yaki29** [comment]
You can also change the android.sdk = "some other version/revision" in the buildozer.spec file, it will do everything from scratch. I know it is little wierd but it worked for me ... (use it as a last option, i.e. if nothing above works for you).

**Comment by Lavz** [comment]
# aidl not found , please install it
#146 yaki29 commented on Nov 1, 2016
You can also change the android.sdk = "some other version/revision" in the buildozer.spec file, it will do everything from scratch. I know it is little wierd but it worked for me ... (use it as a last option, i.e. if nothing above works for you).
**Can you please tell me which sdk version u changed , because past two days i was trying hard to generate APK but not able to do that . finally am getting** 

> **aidl not found , please install it**  

**Can you please tell me how to install AIDL** 
![aidl_error](https://cloud.githubusercontent.com/assets/16485968/22183105/1723679a-e0dc-11e6-9ac8-3c093e81be6a.PNG)

**Comment by yaki29** [comment]
@Lavz Actually I don't remember, it was like 3 months ago. But this issue has been resolved why don't you reinstall the buildozer and also remove the .buildozer directory from where you installed it (probably in your home directory). Perform the same process and I suppose that would work for you.

**Comment by erknrio** [comment]
If you chage the sdk and api version in your buildozer.specs and execute `buildozer android debug deploy run` it download the versions you need automatically and don't need to open graphic app like @kived says.

If you don't know your target version read this:
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html?hl=es-419#ApiLevels

Sorry for my english.

**Comment by urbanonymous** [comment]
Again....

**Comment by RickardHultgren** [comment]
I tried to make updates in the Android SDK Manager but got:
```
Downloading SDK Platform Android 8.1.0, API 27, revision 1
Download finished with wrong size. Expected 65606517 bytes, got 65738431 bytes.
Done. Nothing was installed.
```
Any ideas? Thanks in advance for help!

**Comment by sachgali** [comment]
@Lavz What solution ended up working for you? I have the exact same error you posted above. Been stuck on it for a few days.

**Comment by muronglove** [comment]
1. Run ~/.buildozer/android/platform/android-sdk-21（or20）/tools/android to launch the Android SDK Manager.
2. Install some necessary things.
3. Done

**Comment by kwag** [comment]
As of today, 6/25/2016, it all seems to be broken again.

# Check that aidl can be executed
# Search for Aidl
# Run '/home/karl/.buildozer/android/platform/android-sdk-22/build-tools/19.1.0/aidl'
# Cwd None
# Aidl cannot be executed
#
# You might have missed to install 32bits libs
# Check http://buildozer.readthedocs.org/en/latest/installation.html


And if I try: 

-bash: /home/karl/.buildozer/android/platform/android-sdk-22/build-tools/19.1.0/aidl: cannot execute binary file: Exec format error

32 bits libs are all installed.

No matter if I try it on a VPS running Ubuntu 16.04 or even the VM put together by the team.
I haven't been able to build an APK for the last 3 days.

**Comment by goldern** [comment]
![image](https://user-images.githubusercontent.com/5741155/54733124-9cc6a900-4b76-11e9-9b7b-5b9b95aeaebb.png)
Everything but sdkmanager is installed (?)
Is that the part where they say cygwin64 isn't supported?

**Comment by VaighundaSubash** [comment]
Please help me I'm facing below error,

b"SWT folder '/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/arm' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e

**Comment by seisdr** [comment]
> Please help me I'm facing below error,
> 
> b"SWT folder '/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/arm' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e

find / 2>&1 |grep swt.jar

**Comment by VaighundaSubash** [comment]
Found the swt.jar files in below locations,

/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/jfreechart-1.0.9-swt.jar
/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/x86_64/swt.jar
/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/x86/swt.jar
/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86_64/swt.jar
/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar
/usr/share/java/swt.jar

**Comment by VaighundaSubash** [comment]
> > Please help me I'm facing below error,
> > b"SWT folder '/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/arm' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e
> 
> find / 2>&1 |grep swt.jar

Found the swt.jar files in below locations,

/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/jfreechart-1.0.9-swt.jar
/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/x86_64/swt.jar
/home/pi/.buildozer/android/platform/android-sdk-20/tools/lib/x86/swt.jar
/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86_64/swt.jar
/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar
/usr/share/java/swt.jar

**Comment by VaighundaSubash** [comment]
How to perform "Please export ANDROID_SWT to point to the folder containing swt.jar for your platform" ?

**Comment by seisdr** [comment]
Check what processor you have
`uname -a`
and then use the optimization one 
`
export ANDROID_SWT=/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar
`
Or 

`export ANDROID_SWT=/usr/share/java/swt.jar
`

**Comment by VaighundaSubash** [comment]
> Check what processor you have
> `uname -a`
> and then use the optimization one
> `export ANDROID_SWT=/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar`
> Or
> 
> `export ANDROID_SWT=/usr/share/java/swt.jar `

I have below processor,
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Comment by VaighundaSubash** [comment]
> > Check what processor you have
> > `uname -a`
> > and then use the optimization one
> > `export ANDROID_SWT=/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar`
> > Or
> > `export ANDROID_SWT=/usr/share/java/swt.jar `
> 
> I have below processor,
> Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

Tried
export ANDROID_SWT=/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar
and
export ANDROID_SWT=/usr/share/java/swt.jar

Both are not working. Please suggest me

**Comment by seisdr** [comment]
What error you get

**Comment by VaighundaSubash** [comment]
> What error you get

Still same error

b"SWT folder '/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e

**Comment by VaighundaSubash** [comment]
> > What error you get
> 
> Still same error
> 
> b"SWT folder '/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/swt.jar' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e

After executing the command,
buildozer -v android debug

**Comment by seisdr** [comment]
Yeah make sure it exist also make sure they're not symlinlks

**Comment by VaighundaSubash** [comment]
> Yeah make sure it exist also make sure they're not symlinlks

Couldn't understand

**Comment by seisdr** [comment]
ls -alth /usr/share/java/swt.jar

**Comment by VaighundaSubash** [comment]
> ls -alth /usr/share/java/swt.jar

I have,
lrwxrwxrwx 1 root root 32 Mar 29  2018 /usr/share/java/swt.jar -> ../../lib/java/swt-gtk-3.8.2.jar

**Comment by seisdr** [comment]
export ANDROID_WAT="../../lib/java/swt-gtk-3.8.2.jar"

**Comment by VaighundaSubash** [comment]
> export ANDROID_WAT="../../lib/java/swt-gtk-3.8.2.jar"

Again Buildozer throwing same error. Should we mention where to export? like source and destination path

**Comment by seisdr** [comment]
ANDROID_SWT*
using export is to make sure it set properly otherwise you cand do android_swt=... 
Without export

**Comment by VaighundaSubash** [comment]
> ANDROID_SWT*
> using export is to make sure it set properly otherwise you cand do android_swt=...
> Without export

Again similar error,

b"SWT folder '/usr/share/java/swt.jar' does not exist.\nPlease export ANDROID_SWT to point to the folder containing swt.jar for your platform.\n"# Command failed: /home/pi/.buildozer/android/platform/android-sdk-20/tools/android list sdk -u -e

**Comment by seisdr** [comment]
ANDROID_SWT= ../../lib/java/swt-gtk-3.8.2.jar
and try
Show me
echo $ANDROID_SWT 
and 
ls  -al ../../lib/java/swt-gtk-3.8.2.jar
Might be symlink

**Comment by seisdr** [comment]
Wait

**Comment by seisdr** [comment]
to the folder not the file 
Try 
ANDROID_SWT=/usr/share/java/

**Comment by VaighundaSubash** [comment]
I'm getting below,

pi@raspberrypi:~ $ ANDROID_SWT=/usr/share/java/
pi@raspberrypi:~ $ echo $ANDROID_SWT
/usr/share/java/
pi@raspberrypi:~ $ ls -al ../../lib/java/swt-gtk-3.8.2.jar
ls: cannot access '../../lib/java/swt-gtk-3.8.2.jar': No such file or directory
pi@raspberrypi:~ $

**Comment by seisdr** [comment]
This one should work

export ANDROID_SWT=/home/pi/.buildozer/android/platform/android-sdk/tools/lib/x86/

**Comment by VaighundaSubash** [comment]
Good Improvement!!! Now I got below error,

Aidl not found, please install it

**Comment by seisdr** [comment]
I don't know about this
Maybe apt search aidl

**Comment by VaighundaSubash** [comment]
> I don't know about this
> Maybe apt search aidl

Thank you so much for your great support!!! 

aidl is looks like installation part only. I can continue now

**Comment by AndreMiras** [comment]
Yes this is definitely glitching sometimes, but most of the time it's working.
The workaround is documented in https://buildozer.readthedocs.io/en/latest/installation.html?highlight=aidl#aidl-not-found-please-install-it

**Comment by shervin-glitch** [comment]
what should I do with this ? 
"sdkmanager path "/home/shervin/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" does not exist, sdkmanager is notinstalled"
