### ISSUE TITLE
I'm also experiencing the same issue, using macOS 10.14.3 and no Docker -- just plain Buildozer from the PyPi repo. What is the recommended course of action to fix this?

### ISSUE THREAD

**Issue by kavehmahdavi** [kivy/buildozer#913]
I'm also experiencing the same issue, using macOS 10.14.3 and no Docker -- just plain Buildozer from the PyPi repo. What is the recommended course of action to fix this?

`/.buildozer/android/platform/android-ndk-r17c/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpython3.7m`

_Originally posted by @mgc8 in https://github.com/kivy/buildozer/issues/842#issuecomment-498874316_

**Comment by npetitclerc** [comment]
I believe I'm facing the same issue on macOS Mojave 10.14.5 using Python 3.7

**Install & run steps:**
sudo -H pip3 install --upgrade kivy
sudo -H pip3 install --upgrade buildozer
sudo -H pip3 install --upgrade cython

[cd to my kivy app]
buildozer init
[edit names and set log_level=2]
buildozer -v android debug

With the same error output as https://github.com/kivy/buildozer/issues/842#issuecomment-515839176

**Comment by AndreMiras** [comment]
That should be fixed with `p4a.branch = develop` thanks to @opacam via https://github.com/kivy/python-for-android/pull/1951
also share your `buildozer.spec` and full log when doing bug reports

**Comment by aohan237** [comment]
non-system libraries in linker flags: -lpython3.7m
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the
Android NDK:     current module

@AndreMiras  still cant find -lpython3.7m

**Comment by AndreMiras** [comment]
Weird, I don't know much about OSX, but thanks to opacam we now have it integrated with our CI.
So what I can only recommend to begin with is to compare the build input/output and configurations between yours and our CI.
See last build on both Travis and github actions went green for macOS
https://travis-ci.org/kivy/python-for-android/jobs/621094582
https://github.com/kivy/python-for-android/runs/334852153
To check the configuration read through the p4a Makefile e.g. https://github.com/kivy/python-for-android/blob/2610330/Makefile as well as CI configuration e.g. https://github.com/kivy/python-for-android/blob/2610330/.travis.yml for Travis and https://github.com/kivy/python-for-android/blob/2610330/.github/workflows/push.yml for GitHub Actions.
